# Build web
# FROM golang:1.17-alpine3.15 as web
FROM golang:1.17 AS web

RUN apt-get update && apt-get install -y gcc-aarch64-linux-gnu

RUN mkdir /build
WORKDIR /build
ADD . ./
# RUN CGO_ENABLED=0 GOOS=linux go build -a -o web .
RUN CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc GOOS=linux GOARCH=arm64 go build -o web .



# FROM scratch
FROM multiarch/ubuntu-core:arm64-bionic

WORKDIR /app
COPY --from=web /build/web /app/
#COPY --from=web /build/.env /app/.env
COPY --from=web /build/assets /app/assets
COPY --from=web /build/views /app/views
ENTRYPOINT ["./web"]
